[build]
  publish = "public"
  command = "hugo --minify --gc --enableGitInfo"

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "18"
  GO_VERSION = "1.21"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_VERSION = "0.145.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.145.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.145.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Enable compression
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Encoding = "gzip"

[[headers]]
  for = "*.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"